#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
yarn docgen && git add -A
